import {CHARACTER_DESIGNS} from './character-designs/index.js';
/** 真實畫家；隊伍、戰鬥位置與視覺設定皆為虛構。
 * 年齡以 1888 年 12 月 31 日計。身形比例是角色設計，不是傳記上的實際尺寸。
 * 博物館出處見 docs/ART-WORLD.md 與 docs/CHARACTER-DESIGN.md。
 */
export const HISTORY_DISCLAIMER = '以 1880 年代畫家為靈感的虛構對抗。';
export const FICTION_NOTE = '畫家是真的，隊伍、戰鬥位置、服裝和恩怨都是虛構的。';
export const ROLES = Object.freeze(['vanguard', 'flanker', 'anchor', 'marksman', 'support', 'scout']);
export const FACTIONS = [
  {
    "id": 0,
    "name": "黃屋幫",
    "shortName": "黃屋",
    "color": "#f1ca63",
    "darkColor": "#735321",
    "accent": "#fff0ae",
    "motto": "讓另一種看法有地方站。",
    "description": "一群虛構的色彩實驗者，從梵谷奔放的筆觸到秀拉丈量過的點。",
    "style": "向日葵金、大片色塊，還有辨識度極高的輪廓。",
    "roster": [
      {
        "name": "文森・梵谷",
        "shortName": "梵谷",
        "age1888": 35,
        "role": "vanguard",
        "epithet": "向日葵",
        "artNote": "1888 年，梵谷在亞爾整理黃屋，想弄成畫家共用的工作室。",
        "sourceUrl": "https://www.vangoghmuseum.nl/en/collection/s0032V1962",
        "look": {
          "hat": "frayedstraw",
          "hair": "short",
          "hairColor": "#ae603d",
          "beard": "short",
          "skin": "#dfae88",
          "coat": "smock",
          "trim": "#f4d97a",
          "build": "slim",
          "accessory": "apron",
          "stature": 1,
          "shoulderWidth": 0.9,
          "waistWidth": 0.86,
          "legLength": 1.05,
          "torsoLength": 0.97,
          "headWidth": 0.91,
          "headLength": 1.05,
          "jawWidth": 0.86,
          "noseLength": 1.08,
          "hairline": 0.12,
          "ageLines": 0.35,
          "eyeColor": "#64785e",
          "hatColor": "#bc9d55",
          "hatBandColor": "#735837",
          "coatColor": "#526b63",
          "shirtColor": "#d7c49d",
          "pantsColor": "#514d42",
          "sleeves": "rolled",
          "neckwear": "none",
          "beardShape": "square"
        },
        "personality": {
          "aggression": 0.82,
          "discipline": 0.63,
          "teamwork": 0.76,
          "curiosity": 0.8
        }
      },
      {
        "name": "保羅・高更",
        "shortName": "高更",
        "age1888": 40,
        "role": "flanker",
        "epithet": "色彩狂",
        "artNote": "1888 年 10 月高更到亞爾跟梵谷同住，兩人的畫法時常對不上。",
        "sourceUrl": "https://archive.artic.edu/vangogh/studiosud.html",
        "look": {
          "hat": "slouchberet",
          "hair": "long",
          "hairColor": "#38291f",
          "beard": "moustache",
          "skin": "#c9936d",
          "coat": "doublebreast",
          "trim": "#d69369",
          "build": "broad",
          "accessory": "none",
          "stature": 1.04,
          "shoulderWidth": 1.18,
          "waistWidth": 1.06,
          "legLength": 0.99,
          "torsoLength": 1.07,
          "headWidth": 1.1,
          "headLength": 1.04,
          "jawWidth": 1.13,
          "noseLength": 1.23,
          "noseWidth": 1.15,
          "hairline": 0.1,
          "ageLines": 0.42,
          "hatColor": "#6c4038",
          "coatColor": "#825344",
          "shirtColor": "#c6b89b",
          "pantsColor": "#3f4744",
          "sleeves": "cuffed",
          "neckwear": "kerchief"
        },
        "personality": {
          "aggression": 0.76,
          "discipline": 0.72,
          "teamwork": 0.61,
          "curiosity": 0.91
        }
      },
      {
        "name": "保羅・塞尚",
        "shortName": "塞尚",
        "age1888": 49,
        "role": "anchor",
        "epithet": "那座山",
        "artNote": "1880 年代塞尚的筆觸越來越有秩序，靠顏色堆出形體。",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/paul-cezanne",
        "look": {
          "hat": "none",
          "hair": "bald",
          "hairColor": "#635044",
          "beard": "full",
          "skin": "#d9ad8b",
          "coat": "vest",
          "trim": "#bdb17d",
          "build": "broad",
          "accessory": "waistapron",
          "stature": 0.99,
          "shoulderWidth": 1.1,
          "waistWidth": 1.22,
          "legLength": 0.97,
          "torsoLength": 1.08,
          "headWidth": 1.12,
          "headLength": 0.98,
          "jawWidth": 1.13,
          "noseWidth": 1.13,
          "hairline": 0.88,
          "ageLines": 0.6,
          "stoop": 0.055,
          "coatColor": "#63584f",
          "shirtColor": "#d5c7ab",
          "pantsColor": "#62513f",
          "sleeves": "rolled",
          "neckwear": "none",
          "apronColor": "#bca976",
          "beardShape": "fan"
        },
        "personality": {
          "aggression": 0.46,
          "discipline": 0.88,
          "teamwork": 0.8,
          "curiosity": 0.55
        }
      },
      {
        "name": "喬治・秀拉",
        "shortName": "秀拉",
        "age1888": 29,
        "role": "marksman",
        "epithet": "量過的光",
        "artNote": "1886 年最後一屆印象派畫展上，秀拉首次展出《大碗島的星期天下午》。",
        "sourceUrl": "https://archive.artic.edu/seurat/seurat_themes.html",
        "look": {
          "hat": "none",
          "hair": "short",
          "hairColor": "#332b27",
          "beard": "full",
          "skin": "#ddba9a",
          "coat": "frock",
          "trim": "#d7c7a3",
          "build": "slim",
          "accessory": "none",
          "stature": 1.08,
          "shoulderWidth": 0.92,
          "waistWidth": 0.88,
          "legLength": 1.12,
          "torsoLength": 0.98,
          "headWidth": 0.88,
          "headLength": 1.1,
          "jawWidth": 0.92,
          "noseLength": 1.1,
          "hairline": 0.04,
          "ageLines": 0.08,
          "coatColor": "#3c494a",
          "shirtColor": "#e4d9be",
          "pantsColor": "#3b413e",
          "sleeves": "fitted",
          "neckwear": "stock",
          "beardShape": "pointed"
        },
        "personality": {
          "aggression": 0.4,
          "discipline": 0.98,
          "teamwork": 0.73,
          "curiosity": 0.65
        }
      },
      {
        "name": "保羅・席涅克",
        "shortName": "席涅克",
        "age1888": 25,
        "role": "support",
        "epithet": "港口",
        "artNote": "席涅克是新印象派的要角，1889 年 3 月到亞爾探望好友梵谷。",
        "sourceUrl": "https://vangoghletters.org/vg/letters/let752/letter.html",
        "look": {
          "hat": "sailor",
          "hair": "short",
          "hairColor": "#705039",
          "beard": "full",
          "skin": "#e0b591",
          "coat": "sailor",
          "trim": "#c7b76b",
          "build": "broad",
          "accessory": "none",
          "stature": 1.03,
          "shoulderWidth": 1.12,
          "waistWidth": 1.07,
          "legLength": 1.03,
          "torsoLength": 1.03,
          "headWidth": 1.04,
          "headLength": 0.96,
          "jawWidth": 1.05,
          "noseWidth": 1.05,
          "hairline": 0.03,
          "ageLines": 0.08,
          "hatColor": "#c6c8ae",
          "coatColor": "#304b55",
          "shirtColor": "#d5d6b9",
          "pantsColor": "#374448",
          "sleeves": "cuffed",
          "neckwear": "kerchief"
        },
        "personality": {
          "aggression": 0.38,
          "discipline": 0.83,
          "teamwork": 0.98,
          "curiosity": 0.56
        }
      },
      {
        "name": "亨利・羅特列克",
        "shortName": "羅特列克",
        "age1888": 24,
        "role": "scout",
        "epithet": "夜的速寫",
        "artNote": "羅特列克以描繪表演者和蒙馬特的夜生活成名。",
        "sourceUrl": "https://www.musee-toulouse-lautrec.com/collections/henri-de-toulouse-lautrec/",
        "look": {
          "hat": "bowler",
          "hair": "curly",
          "hairColor": "#3f2c24",
          "beard": "short",
          "skin": "#d9ad8c",
          "coat": "frock",
          "trim": "#bd9767",
          "build": "broad",
          "accessory": "glasses",
          "stature": 0.844444,
          "shoulderWidth": 1.03,
          "waistWidth": 1.08,
          "legLength": 0.68,
          "torsoLength": 1.13,
          "headWidth": 1.08,
          "headLength": 1.02,
          "jawWidth": 1.04,
          "noseLength": 1.05,
          "noseWidth": 1.1,
          "hairline": 0.12,
          "ageLines": 0.13,
          "hatColor": "#393138",
          "hatBandColor": "#b89a63",
          "coatColor": "#634750",
          "shirtColor": "#d9c6a7",
          "pantsColor": "#443d42",
          "sleeves": "fitted",
          "neckwear": "bow",
          "beardShape": "square"
        },
        "personality": {
          "aggression": 0.64,
          "discipline": 0.73,
          "teamwork": 0.72,
          "curiosity": 0.98
        }
      }
    ],
    "facts": [
      {
        "title": "沒真的開成的工作室",
        "text": "梵谷想在黃屋弄一個畫家社群，最後只有高更真的住進去跟他一起畫。遊戲裡這支六人隊伍是虛構的。",
        "url": "https://www.vangoghmuseum.nl/en/collection/s0032V1962"
      },
      {
        "title": "畫法不同還是朋友",
        "text": "1889 年 3 月席涅克到亞爾探望梵谷。兩人技法差很多，交情不受影響。",
        "url": "https://vangoghletters.org/vg/letters/let752/letter.html"
      },
      {
        "title": "顏色與結構",
        "text": "塞尚與印象派往來，同時走自己那套講究秩序的形色路線。",
        "url": "https://www.nationalgallery.org.uk/artists/paul-cezanne"
      }
    ]
  },
  {
    "id": 1,
    "name": "獨立派",
    "shortName": "獨立派",
    "color": "#70cbed",
    "darkColor": "#245568",
    "accent": "#c3edfb",
    "motto": "光要用自己的方式抓。",
    "description": "一群虛構的印象派主將，每個人畫現代生活的方式都不一樣。",
    "style": "鈷藍、發亮的重點色，各自分明的身形。",
    "roster": [
      {
        "name": "克勞德・莫內",
        "shortName": "莫內",
        "age1888": 48,
        "role": "vanguard",
        "epithet": "變動的光",
        "artNote": "1883 年莫內定居吉維尼，專心研究光線變化怎麼改變同一個景。",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/claude-monet",
        "look": {
          "hat": "garden",
          "hair": "short",
          "hairColor": "#79736a",
          "beard": "full",
          "skin": "#d5a681",
          "coat": "smock",
          "trim": "#a9c2bf",
          "build": "broad",
          "accessory": "none",
          "stature": 1.01,
          "shoulderWidth": 1.13,
          "waistWidth": 1.2,
          "legLength": 0.98,
          "torsoLength": 1.05,
          "headWidth": 1.14,
          "headLength": 1.01,
          "jawWidth": 1.13,
          "noseLength": 1.08,
          "noseWidth": 1.17,
          "hairline": 0.3,
          "ageLines": 0.57,
          "hatColor": "#797c59",
          "hatBandColor": "#a9bca8",
          "coatColor": "#617362",
          "shirtColor": "#bfc6b1",
          "pantsColor": "#4c5d55",
          "sleeves": "cuffed",
          "neckwear": "kerchief",
          "beardShape": "fan"
        },
        "personality": {
          "aggression": 0.84,
          "discipline": 0.66,
          "teamwork": 0.82,
          "curiosity": 0.71
        }
      },
      {
        "name": "奧古斯特・雷諾瓦",
        "shortName": "雷諾瓦",
        "age1888": 47,
        "role": "flanker",
        "epithet": "暖光",
        "artNote": "1869 年雷諾瓦和莫內在塞納河邊一起寫生，發展出更亮的色彩與破碎筆觸。",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/pierre-auguste-renoir",
        "look": {
          "hat": "none",
          "hair": "short",
          "hairColor": "#996543",
          "beard": "short",
          "skin": "#e1b595",
          "coat": "vest",
          "trim": "#a8c7e1",
          "build": "slim",
          "accessory": "none",
          "stature": 0.97,
          "shoulderWidth": 0.85,
          "waistWidth": 0.84,
          "legLength": 1.02,
          "torsoLength": 0.97,
          "headWidth": 0.89,
          "headLength": 1.02,
          "jawWidth": 0.85,
          "noseLength": 0.94,
          "noseWidth": 0.87,
          "hairline": 0.65,
          "ageLines": 0.48,
          "stoop": 0.03,
          "coatColor": "#875a53",
          "shirtColor": "#d4c7ab",
          "pantsColor": "#51484c",
          "sleeves": "rolled",
          "neckwear": "bow"
        },
        "personality": {
          "aggression": 0.73,
          "discipline": 0.78,
          "teamwork": 0.81,
          "curiosity": 0.89
        }
      },
      {
        "name": "艾德加・竇加",
        "shortName": "竇加",
        "age1888": 54,
        "role": "anchor",
        "epithet": "動作",
        "artNote": "竇加跟印象派一起展出，用素描、油畫和粉彩研究現代生活。",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/hilaire-germain-edgar-degas",
        "look": {
          "hat": "none",
          "hair": "bald",
          "hairColor": "#8b8274",
          "beard": "short",
          "skin": "#d9b493",
          "coat": "doublebreast",
          "trim": "#aebdd1",
          "build": "average",
          "accessory": "none",
          "stature": 1.025,
          "shoulderWidth": 1.01,
          "waistWidth": 1.03,
          "legLength": 1.04,
          "torsoLength": 1.01,
          "headWidth": 0.96,
          "headLength": 1.08,
          "jawWidth": 1.03,
          "noseLength": 1.18,
          "hairline": 0.79,
          "ageLines": 0.72,
          "stoop": 0.07,
          "coatColor": "#444951",
          "shirtColor": "#c2c6bd",
          "pantsColor": "#3b424c",
          "sleeves": "fitted",
          "neckwear": "cravat",
          "beardShape": "square"
        },
        "personality": {
          "aggression": 0.47,
          "discipline": 0.94,
          "teamwork": 0.79,
          "curiosity": 0.5
        }
      },
      {
        "name": "貝爾特・莫利索",
        "shortName": "莫利索",
        "age1888": 47,
        "role": "marksman",
        "epithet": "戶外",
        "artNote": "莫利索是印象派的核心成員，與莫內、雷諾瓦、竇加、畢沙羅一同展出。",
        "sourceUrl": "https://www.marmottan.fr/collections/berthe-morisot/",
        "look": {
          "hat": "bonnet",
          "hair": "waved",
          "hairColor": "#aca39b",
          "beard": "none",
          "skin": "#e4bc9f",
          "coat": "highcollar",
          "trim": "#d6be8b",
          "build": "slim",
          "accessory": "shawl",
          "presentation": "woman",
          "stature": 0.975,
          "shoulderWidth": 0.82,
          "waistWidth": 0.88,
          "legLength": 1.03,
          "torsoLength": 0.99,
          "headWidth": 0.87,
          "headLength": 1.08,
          "jawWidth": 0.8,
          "noseLength": 1.05,
          "noseWidth": 0.83,
          "hairline": 0.12,
          "ageLines": 0.53,
          "hatColor": "#414654",
          "hatBandColor": "#aaa6b5",
          "coatColor": "#53657d",
          "shirtColor": "#c6c8bf",
          "pantsColor": "#444c61",
          "sleeves": "puff",
          "neckwear": "none"
        },
        "personality": {
          "aggression": 0.45,
          "discipline": 0.94,
          "teamwork": 0.65,
          "curiosity": 0.72
        }
      },
      {
        "name": "卡米耶・畢沙羅",
        "shortName": "畢沙羅",
        "age1888": 58,
        "role": "support",
        "epithet": "果園",
        "artNote": "畢沙羅 1886 年改走新印象派，1890 年又回到比較自由的筆法。",
        "sourceUrl": "https://www.ashmolean.org/view-my-window",
        "look": {
          "hat": "floppy",
          "hair": "bald",
          "hairColor": "#d6d1c4",
          "beard": "full",
          "skin": "#d8ad8b",
          "coat": "smock",
          "trim": "#9fc6d0",
          "build": "slim",
          "accessory": "glasses",
          "stature": 0.985,
          "shoulderWidth": 0.95,
          "waistWidth": 1.02,
          "legLength": 1,
          "torsoLength": 1,
          "headWidth": 0.96,
          "headLength": 1.09,
          "jawWidth": 0.96,
          "noseLength": 1.2,
          "noseWidth": 1.05,
          "hairline": 0.92,
          "ageLines": 0.92,
          "stoop": 0.12,
          "hatColor": "#8d8978",
          "hatBandColor": "#6b766f",
          "coatColor": "#827257",
          "shirtColor": "#cad0c2",
          "pantsColor": "#566066",
          "sleeves": "cuffed",
          "neckwear": "kerchief",
          "beardShape": "flowing"
        },
        "personality": {
          "aggression": 0.37,
          "discipline": 0.85,
          "teamwork": 0.98,
          "curiosity": 0.68
        }
      },
      {
        "name": "瑪麗・卡薩特",
        "shortName": "卡薩特",
        "age1888": 44,
        "role": "scout",
        "epithet": "現代之眼",
        "artNote": "卡薩特 1879 年加入印象派畫展，1880、1881、1886 年再度參展。",
        "sourceUrl": "https://www.metmuseum.org/essays/mary-stevenson-cassatt-1844-1926",
        "look": {
          "hat": "portrait",
          "hair": "pinned",
          "hairColor": "#745344",
          "beard": "none",
          "skin": "#e2b392",
          "coat": "cape",
          "trim": "#d5a29b",
          "build": "average",
          "accessory": "capelet",
          "presentation": "woman",
          "stature": 1.015,
          "shoulderWidth": 1.02,
          "waistWidth": 1.08,
          "legLength": 1.01,
          "torsoLength": 1.05,
          "headWidth": 1.07,
          "headLength": 0.98,
          "jawWidth": 0.99,
          "noseLength": 0.97,
          "noseWidth": 1.02,
          "hairline": 0.08,
          "ageLines": 0.43,
          "hatColor": "#6e526a",
          "hatBandColor": "#abc4d1",
          "coatColor": "#675c7a",
          "shirtColor": "#d7cebf",
          "pantsColor": "#4b4b62",
          "sleeves": "puff",
          "neckwear": "none"
        },
        "personality": {
          "aggression": 0.58,
          "discipline": 0.83,
          "teamwork": 0.73,
          "curiosity": 0.97
        }
      }
    ],
    "facts": [
      {
        "title": "各走各的路",
        "text": "這些畫家都參與過印象派運動。遊戲裡的隊名只是取名，不代表他們是「獨立藝術家協會」的成員。",
        "url": "https://www.nationalgallery.org.uk/artists/hilaire-germain-edgar-degas"
      },
      {
        "title": "莫利索的位置",
        "text": "莫利索是印象派的核心成員，地位與莫內、雷諾瓦、竇加、畢沙羅並列。",
        "url": "https://www.marmottan.fr/collections/berthe-morisot/"
      },
      {
        "title": "卡薩特參展紀錄",
        "text": "受竇加邀請，卡薩特在 1879、1880、1881、1886 年與印象派一同展出。",
        "url": "https://www.metmuseum.org/essays/mary-stevenson-cassatt-1844-1926"
      },
      {
        "title": "換過畫法又換回來",
        "text": "畢沙羅 1886 年起試了新印象派，到 1890 年又回頭用比較自由的筆法。",
        "url": "https://www.ashmolean.org/view-my-window"
      }
    ]
  }
];
export const FACTION_BY_ID = Object.fromEntries(FACTIONS.map(faction => [faction.id, faction]));

// 同一份角色設定同時餵給模型、動作和特寫肖像。
for(const faction of FACTIONS)for(const artist of faction.roster){
 const design=CHARACTER_DESIGNS[artist.shortName];
 artist.design=design;
 artist.look={...artist.look,...design.look,characterId:design.id,age1888:artist.age1888,face:{...design.face},motion:{...design.motion},tailoring:{...design.tailoring}};
}
